# Generated by Django 5.2.16 on 2026-07-22 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_id', models.CharField(blank=True, db_index=True, help_text='Auto-generated on submit.  Format: BK-YYYYMM-XXXX', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_HOD_APPROVAL', 'Pending HOD Approval'), ('PENDING_ALLOTMENT', 'Pending Allotment'), ('PENDING_MANAGEMENT_APPROVAL', 'Pending Management Approval'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=35)),
                ('mobile_number', models.CharField(help_text='Contact number for this booking (may differ from profile).', max_length=15)),
                ('is_faculty_incharge', models.BooleanField(default=False, help_text='True if the requestor is themselves the Faculty In-Charge.')),
                ('incharge_name', models.CharField(blank=True, max_length=150)),
                ('incharge_email', models.EmailField(blank=True, max_length=254)),
                ('incharge_mobile', models.CharField(blank=True, max_length=15)),
                ('campus_id', models.PositiveIntegerField(blank=True, help_text='References room_inventory.Campus.pk (no FK constraint for now).', null=True)),
                ('campus_name', models.CharField(blank=True, help_text='Denormalised campus name for display without a JOIN.', max_length=150)),
                ('purpose_of_booking', models.TextField(help_text='Mandatory. Reason this accommodation is being requested.')),
                ('event_id', models.PositiveIntegerField(blank=True, null=True)),
                ('event_name', models.CharField(blank=True, max_length=250)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('num_guests_male', models.PositiveIntegerField(default=0)),
                ('num_guests_female', models.PositiveIntegerField(default=0)),
                ('num_rooms_required', models.PositiveIntegerField(default=1)),
                ('is_foreign_guest', models.BooleanField(default=False, help_text='Triggers Form C requirement when True.')),
                ('preferred_guest_house_id', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_guest_house_name', models.CharField(blank=True, max_length=250)),
                ('room_configuration', models.CharField(blank=True, help_text='E.g. Single, Double, Suite.', max_length=100)),
                ('special_requests', models.TextField(blank=True)),
                ('food_arrangement', models.CharField(choices=[('UNIVERSITY', 'University'), ('DEPARTMENT', 'Department'), ('SELF', 'Self'), ('NOT_REQUIRED', 'Not Required')], default='NOT_REQUIRED', max_length=20)),
                ('travel_arrangement', models.CharField(choices=[('UNIVERSITY', 'University'), ('DEPARTMENT', 'Department'), ('SELF', 'Self'), ('NOT_REQUIRED', 'Not Required')], default='NOT_REQUIRED', max_length=20)),
                ('local_transport_arrangement', models.CharField(choices=[('UNIVERSITY', 'University'), ('DEPARTMENT', 'Department'), ('SELF', 'Self'), ('NOT_REQUIRED', 'Not Required')], default='NOT_REQUIRED', max_length=20)),
                ('payment_arrangement', models.CharField(choices=[('GUEST', 'Guest Pays'), ('DEPARTMENT', 'Department'), ('UNIVERSITY', 'University')], default='GUEST', max_length=20)),
                ('room_sharing_grouping', models.TextField(blank=True, help_text='Notes on how guests should be grouped for room sharing.')),
                ('rejection_reason', models.TextField(blank=True)),
                ('rejection_stage', models.CharField(blank=True, help_text='Status value at the time of rejection, for audit trail.', max_length=35)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_bookings', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(help_text='The user who created this booking request.', on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Request',
                'verbose_name_plural': 'Booking Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlternateContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternate_contacts', to='booking.bookingrequest')),
            ],
            options={
                'verbose_name': 'Alternate Contact',
                'verbose_name_plural': 'Alternate Contacts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other / Prefer not to say')], max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('guest_type', models.CharField(choices=[('DOMESTIC', 'Domestic'), ('FOREIGN', 'Foreign')], default='DOMESTIC', max_length=10)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('disability_needs', models.TextField(blank=True, help_text='Accessibility or disability accommodation requirements.')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='booking.bookingrequest')),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['requestor', 'status'], name='booking_boo_request_0ff929_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['status', 'created_at'], name='booking_boo_status_204cc5_idx'),
        ),
    ]
