# Generated by Django 5.2.16 on 2026-07-24 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('room_inventory', '0003_alter_room_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='allotted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allotted_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='allotted_guest_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allotted_guesthouse_bookings', to='room_inventory.guesthouse'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='allotted_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allotted_bookings', to='room_inventory.room'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='hod_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_approved_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='hold_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='management_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='management_approved_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='proposed_guest_house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_guesthouse_bookings', to='room_inventory.guesthouse'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='proposed_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='proposed_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_bookings', to='room_inventory.room'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='query_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='query_stage',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='query_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='booking_id',
            field=models.CharField(blank=True, db_index=True, help_text='Auto-generated on submit. Format: BK-YYYYMM-XXXX', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='campus_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='campus_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='rejection_stage',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='room_sharing_grouping',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_HOD_APPROVAL', 'Pending HOD Approval'), ('PENDING_ALLOTMENT', 'Pending Room Allotment'), ('ALTERNATIVE_PROPOSED', 'Alternative Room Proposed'), ('PENDING_MANAGEMENT_APPROVAL', 'Pending Management Approval'), ('ON_HOLD', 'On Hold'), ('QUERY_RAISED', 'Query / Clarification Required'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=35),
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_name', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('previous_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='booking.bookingrequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Approval History',
                'verbose_name_plural': 'Approval Histories',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='booking.bookingrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
