# Generated by Django 5.2.16 on 2026-07-24 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Optional icon identifier or emoji', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='guesthouse',
            options={'ordering': ['name'], 'verbose_name': 'Guest House', 'verbose_name_plural': 'Guest Houses'},
        ),
        migrations.AddField(
            model_name='guesthouse',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='guesthouse',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_houses', to='room_inventory.campus'),
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('default_capacity', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('guest_house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='room_inventory.guesthouse')),
            ],
            options={
                'verbose_name': 'Room Category',
                'verbose_name_plural': 'Room Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(max_length=50)),
                ('floor', models.CharField(default='1', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BLOCKED', 'Blocked'), ('UNDER_MAINTENANCE', 'Under Maintenance')], db_index=True, default='AVAILABLE', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='rooms', to='room_inventory.amenity')),
                ('guest_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='room_inventory.guesthouse')),
                ('room_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='room_inventory.roomcategory')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['guest_house', 'room_number'],
                'unique_together': {('guest_house', 'room_number')},
            },
        ),
    ]
