# Generated by Django 5.2.16 on 2026-07-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_inventory', '0002_amenity_alter_guesthouse_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('VACANT_CLEAN', 'Vacant Clean'), ('VACANT_DIRTY', 'Vacant Dirty'), ('CLEANING_IN_PROGRESS', 'Cleaning In Progress'), ('OCCUPIED', 'Occupied'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('BLOCKED', 'Blocked')], db_index=True, default='VACANT_CLEAN', max_length=30),
        ),
    ]
